/* Generated By:JavaCC: Do not edit this line. simplejavaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface simplejavaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ELSE = 6;
  /** RegularExpression Id. */
  int FOR = 7;
  /** RegularExpression Id. */
  int WHILE = 8;
  /** RegularExpression Id. */
  int DO = 9;
  /** RegularExpression Id. */
  int TRUE = 10;
  /** RegularExpression Id. */
  int FALSE = 11;
  /** RegularExpression Id. */
  int CLASS = 12;
  /** RegularExpression Id. */
  int LEFT_PARENTHESIS = 13;
  /** RegularExpression Id. */
  int RIGHT_PARENTHESIS = 14;
  /** RegularExpression Id. */
  int LEFT_CURLY_BRACE = 15;
  /** RegularExpression Id. */
  int RIGHT_CURLY_BRACE = 16;
  /** RegularExpression Id. */
  int LEFT_SQUARE_BRACE = 17;
  /** RegularExpression Id. */
  int RIGHT_SQUARE_BRACE = 18;
  /** RegularExpression Id. */
  int IF = 19;
  /** RegularExpression Id. */
  int RETURN = 20;
  /** RegularExpression Id. */
  int NEW = 21;
  /** RegularExpression Id. */
  int PLUS = 22;
  /** RegularExpression Id. */
  int MINUS = 23;
  /** RegularExpression Id. */
  int TIMES = 24;
  /** RegularExpression Id. */
  int DIVIDE = 25;
  /** RegularExpression Id. */
  int DOT = 26;
  /** RegularExpression Id. */
  int COMMA = 27;
  /** RegularExpression Id. */
  int SEMICOLON = 28;
  /** RegularExpression Id. */
  int GETS = 29;
  /** RegularExpression Id. */
  int EQUALS = 30;
  /** RegularExpression Id. */
  int NOT_EQUALS = 31;
  /** RegularExpression Id. */
  int INC_DOWN = 32;
  /** RegularExpression Id. */
  int INC_UP = 33;
  /** RegularExpression Id. */
  int LESS_THAN = 34;
  /** RegularExpression Id. */
  int GREATER_THAN = 35;
  /** RegularExpression Id. */
  int LESS_THAN_OR_EQUAL = 36;
  /** RegularExpression Id. */
  int GREATER_THAN_OR_EQUAL = 37;
  /** RegularExpression Id. */
  int AND = 38;
  /** RegularExpression Id. */
  int OR = 39;
  /** RegularExpression Id. */
  int NOT = 40;
  /** RegularExpression Id. */
  int IDENTIFIER = 41;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 42;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 4>",
    "\"/*\"",
    "\"else\"",
    "\"for\"",
    "\"while\"",
    "\"do\"",
    "\"true\"",
    "\"false\"",
    "\"class\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"if\"",
    "\"return\"",
    "\"new\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\".\"",
    "\",\"",
    "\";\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\"--\"",
    "\"++\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "<IDENTIFIER>",
    "<INTEGER_LITERAL>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 45>",
  };

}
